USE cake_akazeep;




INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (7,null,null,null,'شرطة_بوسطن_تعتقل_المشتبه_به_الثاني_في_التفجيرات_وتؤكد_1','علنت شرطة مدينة بوسطن الأمريكية، السبت، أن المشتبه به الثاني في تفجيري ماراثون بوسطن رهن الاحتجاز الآن، بعدما تم اعتقاله في وقت مبكر صباح السبت.أضافت الشرطة في تغريدة عبر حسابها الرسمي على موقع ''''تويتر'''': ''''المطاردة انتهت، والإرهاب انتهى، وانتصرت العدالة''''.',' شرطة ''''بوسطن'''' تعتقل المشتبه به الثاني في التفجيرات.. وتؤكد: انتصرت العدالة ',null,null,9,1,0,'2013-04-20 12:33:11','2013-04-20 12:35:56');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (8,null,null,null,'مصدر_أمني_ارتفاع_عدد_المقبوض_عليهم_في_أحداث_تطهير_القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.
','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-04-20 12:48:05','2013-04-20 12:48:05');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (9,null,null,null,'قاضي_خلية_مدينة_نصر_يرفع_الجلسة_بعد_مشادة_مع_المتهمين_ل_1','قرر المستشار شعبان عبد الرحمن الشامي، رئيس الدائرة 15 بمحكمة جنايات شمال القاهرة، رفع أولى جلسات محاكمة 26 متهمًا في قضية خلية مدينة نصر الإرهابية، بعد أن وقعت مشادات كلامية بين المتهمين، والقاضي عقب قراره باحتجاز أحد المتهمين في قفص انفرادي.','قاضي «خلية مدينة نصر» يرفع الجلسة بعد مشادة مع المتهمين لوصفه بـ«الفلول»',null,null,0,1,0,'2013-04-20 12:50:20','2013-04-20 12:50:20');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (10,null,null,null,'المركزي_لم_نتسلم_وديعة_قطر_ولن_نستنزف_الاحتياطي_للقضا','قال هشام رامز، محافظ البنك المركزي المصري، إن الوديعة القطرية الجديدة البالغة  3 مليارات دولار لشراء سندات، لم تصل مصر بعد، موضحا أنه لم يكن طرفا في الحوار مع قطر أو ليبيا حول المساندة المالية، وأنه كان قد زار قطر قبيل الإعلان عن المساندة للاشتراك في اجتماع مالي عربي، وليس لأي هدف آخر.',' «المركزي»: لم نتسلم وديعة قطر.. ولن نستنزف الاحتياطي للقضاء على السوق السوداء',null,null,0,1,0,'2013-04-20 12:51:55','2013-04-20 12:51:55');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (11,null,null,null,'اتفاقية-تعاون-إعلامي-بين-التليفزيون-المصري-ونظيره-الت','تم اليوم السبت توقيع اتفاقية تعاون إعلامي بين مصر وتركيا في مجال التبادل الإخباري والبرامجي والدرامي والتقني.','اتفاقية تعاون إعلامي بين التليفزيون المصري ونظيره التركي',null,null,9,1,0,'2013-04-20 19:40:19','2013-04-20 19:40:19');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (12,null,'518edebe-b83c-44b3-88e5-20f05c0f8f43.jpg','518edebe-3b44-46a7-929f-20f05c0f8f43.jpg','-الادارية-العليا-تؤيد-حكم-وقف-انتخابات-مجلس-النواب--1','قضت دائرة الموضوع بالمحكمة الإدارية العليا برئاسة المستشار يحيى الدكرور، اليوم الأحد، برفض الطعن المقدم من هيئة قضايا الدولة، وكيلاً عن كل من الدكتور محمد مرسى رئيس الجمهورية، والدكتور أحمد فهمي، رئيس مجلس الشورى، والمستشار أحمد مكى وزير العدل، ومحمد العمدة عضو مجلس العب السابق على الحكم الصادر من محكمة أول ',' الادارية العليا تؤيد حكم وقف انتخابات مجلس النواب ',null,null,517,1,0,'2013-04-21 19:03:22','2013-05-12 02:13:50');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (13,null,'51742c02-7754-415c-8f28-07045c0f8f43.jpg','51742c02-3e14-4296-8cbc-07045c0f8f43.jpg','قاضي-رفض-ممثل-النيابة-التفتيش-القضائي-تفهم-موقفي-وانته-1','أكد المستشار رواد محمد حما، القاضي بمحكمة الجنح، أنه أدلى بأقواله اليوم الأحد، أمام جهاز التفتيش القضائي بوزارة العدل، على خلفية استدعائه للتحقيق بعد أن أصدر قراراً ببطلان انعقاد أحد الجلسات لبطلان تمثيل النيابة العامة لصدر حكم من دائرة طلبات رجال القضاء ببطلان تعين المستشار طلعت إبراهيم النائب العام في منصبه.','قاضي ''''رفض ممثل النيابة'''': التفتيش القضائي تفهم موقفي وانتهى الأمر',null,null,0,1,0,'2013-04-21 20:12:18','2013-04-21 20:12:18');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (14,null,'517444f1-a4ec-4292-8695-07045c0f8f43.jpg','517444f1-18b8-4222-9364-07045c0f8f43.jpg','2222قاضي-رفض-ممثل-النيابة-التفتيش-القضائي-تفهم-موقفي-وان-1','أكد المستشار رواد محمد حما، القاضي بمحكمة الجنح، أنه أدلى بأقواله اليوم الأحد، أمام جهاز التفتيش القضائي بوزارة العدل، على خلفية استدعائه للتحقيق بعد أن أصدر قراراً ببطلان انعقاد أحد الجلسات لبطلان تمثيل النيابة العامة لصدر حكم من دائرة طلبات رجال القضاء ببطلان تعين المستشار طلعت إبراهيم النائب العام في منصبه.','2222قاضي ''''رفض ممثل النيابة'''': التفتيش القضائي تفهم موقفي وانتهى الأمر',null,null,0,1,0,'2013-04-21 21:58:41','2013-04-21 21:58:41');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (15,null,'51744529-1d98-47a9-a55c-07045c0f8f43.htm','51744529-aaa4-443d-9e3f-07045c0f8f43.jpg','2222قاضي-رفض-ممثل-النيابة-التفتيش-القضائي-تفهم-موقفي-وان-2','أكد المستشار رواد محمد حما، القاضي بمحكمة الجنح، أنه أدلى بأقواله اليوم الأحد، أمام جهاز التفتيش القضائي بوزارة العدل، على خلفية استدعائه للتحقيق بعد أن أصدر قراراً ببطلان انعقاد أحد الجلسات لبطلان تمثيل النيابة العامة لصدر حكم من دائرة طلبات رجال القضاء ببطلان تعين المستشار طلعت إبراهيم النائب العام في منصبه.','2222قاضي ''''رفض ممثل النيابة'''': التفتيش القضائي تفهم موقفي وانتهى الأمر',null,null,0,1,0,'2013-04-21 21:59:37','2013-04-21 21:59:37');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (16,null,null,null,'كذبة-جديدة-1','كذبة جديدة','كذبة جديدة',null,null,0,1,0,'2013-05-05 14:42:40','2013-05-05 14:42:40');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (17,null,null,'51879a88-4028-4904-b5e7-20f05c0f8f43.jpg','hello-world-1','hello world','hello world',null,null,0,1,0,'2013-05-06 13:56:56','2013-05-06 13:56:56');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (18,null,'','','مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 14:29:57','2013-05-11 14:29:57');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (19,null,'cute-baby[1].jpg','cute-baby[1].jpg','مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:25:05','2013-05-11 15:25:05');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (20,null,'cute-baby[1].jpg','cute-baby[1].jpg','مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:26:39','2013-05-11 15:26:39');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (21,null,'cute-baby[1].jpg','cute-baby[1].jpg','مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:27:27','2013-05-11 15:27:27');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (22,null,'cute-baby[1].jpg','cute-baby[1].jpg','مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:28:30','2013-05-11 15:28:30');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (23,null,'cute-baby[1].jpg','cute-baby[1].jpg','مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:29:50','2013-05-11 15:29:50');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (24,null,null,null,'مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:31:10','2013-05-11 15:31:10');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (25,null,null,null,'مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:32:42','2013-05-11 15:32:42');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (26,null,null,null,'مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:36:38','2013-05-11 15:36:38');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (27,null,'cute-baby[1].jpg','cute-baby[1].jpg','مصدر-أمني-ارتفاع-عدد-المقبوض-عليهم-في-أحداث-تطهير-القض','ارتفع عدد المقبوض عليهم في اشتباكات جمعة «تطهير القضاء» إلى 39 متهمًا، وقالت التحريات إنهم شاركوا في أعمال الشغب والعنف التي وقعت في شارع رمسيس بداية من كوبري أكتوبر، وإن من بين المقبوض عليهم 3 متهمين بحرق أتوبيس لجماعة الإخوان المسلمين، و16 آخرين ألقوا الحجارة والخرطوش على قوات الأمن.','مصدر أمني: ارتفاع عدد المقبوض عليهم في أحداث «تطهير القضاء» إلى 39 متهمًا',null,null,0,1,0,'2013-05-11 15:39:51','2013-05-11 15:39:51');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (28,null,'518e5552-2e30-4e10-88a1-20f05c0f8f43.jpg','518e540f-a0c0-4756-902d-20f05c0f8f43.jpg','hello-1','hello','hello',null,null,0,0,0,'2013-05-11 15:41:01','2013-05-11 16:27:30');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (29,null,'naab2_20121223144820[1].jpg','naab2_20121223144820[1].jpg','hello-2','hello','hello',null,null,0,0,0,'2013-05-11 15:42:10','2013-05-11 15:42:10');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (30,null,null,null,'hello-3','hello','hello',null,null,0,0,0,'2013-05-11 15:51:39','2013-05-11 15:51:39');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (31,null,null,null,'hello-4','hello','hello',null,null,0,0,0,'2013-05-11 16:07:53','2013-05-11 16:07:53');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (32,null,'518e50dd-d678-4e1d-af12-20f05c0f8f43.jpg','518e50dd-cbd0-4191-b3c5-20f05c0f8f43.jpg','hello-5','hello','hello',null,null,0,1,0,'2013-05-11 16:08:29','2013-05-11 16:08:29');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (33,null,null,'518e5132-4698-449b-acb2-20f05c0f8f43.jpg','hello-6','hello','hello',null,null,0,0,0,'2013-05-11 16:09:54','2013-05-11 16:09:54');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (34,null,null,'518e5215-4368-44c4-aece-20f05c0f8f43.jpg','hello22222-1','hello','hello22222',null,null,0,0,0,'2013-05-11 16:13:41','2013-05-11 16:13:41');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (35,null,null,'518e52b2-a540-4716-9ddd-20f05c0f8f43.jpg','hello-7','hello','hello',null,null,0,0,0,'2013-05-11 16:16:18','2013-05-11 16:16:18');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (36,null,'518e560e-e638-47e1-8b0b-20f05c0f8f43.jpg','518e560e-5dd0-4371-a226-20f05c0f8f43.jpg','none-1','this me','none',null,null,0,1,0,'2013-05-11 16:30:38','2013-05-11 16:30:38');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (37,null,'518e59d4-300c-4029-a1e2-20f05c0f8f43.jpg','518e59d4-0fe8-448c-a7a9-20f05c0f8f43.jpg','test-1','test','test',null,null,517,0,0,'2013-05-11 16:46:44','2013-05-11 16:46:44');
INSERT INTO `cake_akazeep`.`aka_posts`(`id`,`keywords`,`correction_image`,`post_image`,`url`,`summary`,`title`,`description`,`correction`,`user_id`,`allow_comments`,`is_published`,`created`,`modified`) VALUES (38,null,'51975703-8000-4bd0-be7e-17985c0f8f43.jpg','51975703-9708-4dd0-a688-17985c0f8f43.jpg','خاطفو-الجنود-بسيناء-يغيرون-أماكنهم-لتشتيت-التتبع-الأم','خاطفو الجنود بسيناء يغيرون أماكنهم لتشتيت التتبع الأمني<خاطفو الجنود بسيناء يغيرون أماكنهم لتشتيت التتبع الأمني<خاطفو الجنود بسيناء يغيرون أماكنهم لتشتيت التتبع الأمني','خاطفو الجنود بسيناء يغيرون أماكنهم لتشتيت التتبع الأمني',null,null,517,1,0,'2013-05-18 12:25:07','2013-05-18 12:25:07');
